version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: sushrusa_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - sushrusa_network

volumes:
  redis_data:

networks:
  sushrusa_network:
    driver: bridge 